In [5]:
import pandas as pd
from sqlalchemy import create_engine

In [9]:
import pandas as pd
from sqlalchemy import create_engine

# Connect to MySQL
username = "dc_user"
password = "1234"
host = "localhost"
database = "dcidb"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}/{database}")

# Load data from the correct table
df = pd.read_sql("SELECT * FROM campaigns", engine)

# Check first 5 rows
df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.6,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.6,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.6,0.8,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [10]:
df = df.drop_duplicates()

In [11]:
df.duplicated().sum()  # should be 0

0

In [12]:
df = df.fillna("Unknown")

In [14]:
df.columns

Index(['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration',
       'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions',
       'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score',
       'Customer_Segment', 'Date'],
      dtype='str')

In [16]:
df = df.drop_duplicates()

numeric_cols = ['Revenue', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Revenue', 
                'Acquisition_Cost', 'ROI', 'Engagement_Score', 'Duration']

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna({
    'Impressions': 0,
    'Clicks': 0,
    'Leads': 0,
    'Conversions': 0,
    'Revenue': df['Revenue'].mean(),
    'Acquisition_Cost': df['Acquisition_Cost'].mean(),
    'ROI': 0,
    'Engagement_Score': 0,
    'Duration': df['Duration'].mean()
}, inplace=True)

text_cols = ['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Channel_Used', 'Language', 'Customer_Segment', 'Date']
df[text_cols] = df[text_cols].fillna('Unknown')

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

df = df[df['revenue'] > 0]

df.info()
df.head()

C:\Users\mprat\AppData\Local\Temp\ipykernel_2324\1225856577.py:25: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object'):

<class 'pandas.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   campaign_id       55555 non-null  str
 1   campaign_type     55555 non-null  str
 2   target_audience   55555 non-null  str
 3   duration          55555 non-null  int64
 4   channel_used      55555 non-null  str
 5   impressions       55555 non-null  int64
 6   clicks            55555 non-null  int64
 7   leads             55555 non-null  int64
 8   conversions       55555 non-null  int64
 9   revenue           55555 non-null  int64
 10  acquisition_cost  55555 non-null  float64
 11  roi               55555 non-null  float64
 12  language          55555 non-null  str
 13  engagement_score  55555 non-null  float64
 14  customer_segment  55555 non-null  str
 15  date              55555 non-null  str
dtypes: float64(3), int64(6), str(7)
memory usage: 6.8 MB

,campaign_id,campaign_type,target_audience,duration,channel_used,impressions,clicks,leads,conversions,revenue,acquisition_cost,roi,language,engagement_score,customer_segment,date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [17]:
df.to_sql('campaigns', con=engine, if_exists='replace', index=False)

55555

In [18]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://dc_user:1234@localhost/dcidb")

df.to_sql('cleaned_campaigns', con=engine, if_exists='replace', index=False)

55555